# Generated by Django 4.2.9 on 2023-12-30 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Valhalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.game')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Spear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.game')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.game')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Hammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.game')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Flail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.game')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Dagger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.game')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='CreedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('character_image_url', models.URLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creed_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('creed_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='creedapi.creeduser')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.game')),
            ],
        ),
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.game')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.game')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creedapi.weapon')),
            ],
        ),
    ]
